##############################
###### DATABASE SETTINGS #####
##############################
spring:
  datasource:
    url: jdbc:postgresql://${SERVER_URI}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
#  sql:
#    init:
#      data-locations: classpath:data.sql
#      mode: always
#      platform: postgresql


##############################
######## JPA SETTINGS ########
##############################
  jpa:
#    show-sql: true
    hibernate:
      # <create | create-drop | update | validate | none>
      ddl-auto: create-drop
    open-in-view: false